export { default as About } from './About';
export * from './AddShipView/AddShipView';
export * from './DashboardView/DashboardView';
export { default as Error } from './Error';
export { default as Home } from './Home';
export * from './LoginView/LoginView';
export * from './RegisterView/RegisterView';
export * from './ShipsView/ShipsView';
export * from './UpdateShipView/UpdateShipView';
export * from './index';
