export { default as About } from './About'
export * from './DashboardView/DashboardView'
export { default as Error } from './Error'
export { default as Home } from './Home'
export * from './Ships/Ships'
